name: Build package

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        type: choice
        description: 'Debian/Ubuntu Version'
        options:
          - 'bookworm'
          - 'bullseye'
          - 'buster'
        required: true

jobs:
  build-debs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os-version: ["buster", "bullseye", "bookworm"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1.8.0
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ matrix.os-version }}"
          host-arch: "${{ matrix.arch }}"
          extra-build-deps: devscripts git
          before-build-hook: "dch --local ~${{ matrix.os-version }} 'GitHub build for ${{ matrix.os-version }}'"
          buildpackage-opts: --build=binary --no-sign
      - name: Upload deb files
        uses: actions/upload-artifact@v4.3.3
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
          path: ./debian/artifacts/*

  merge-artefacts:
    runs-on: ubuntu-latest
    needs: build-debs
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4

  add_release:
    name: Add package to release
    needs: merge-artefacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: debian-packages
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.deb

  add_repo:
    runs-on: ubuntu-latest
    needs: build-debs
    strategy:
      max-parallel: 1
      matrix:
        os-version: ["buster", "bullseye", "bookworm"]
        arch: ["amd64", "arm64"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
      - name: Add ${{ matrix.arch }} release
        uses: smeinecke/apt-repo-action@v2.1.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          repo_supported_arch: ${{ matrix.arch }}
          repo_supported_version: |
            buster
            bullseye
            bookworm
          file: |
            *-${{ matrix.os-version }}*.deb
          file_target_version: ${{ matrix.os-version }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""

