name: Manually build package

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        type: choice
        description: 'Debian/Ubuntu Version'
        options:
          - 'bookworm'
          - 'bullseye'
          - 'buster'
        required: true
      arch:
        type: choice
        description: 'Architecture'
        options:
          - 'amd64'
          - 'arm64'
        required: true

jobs:
  build-debs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build Debian packages
        uses: jtdor/build-deb-action@v1.8.0
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: "debian:${{ inputs.flavor }}"
          host-arch: "${{ inputs.arch }}"
          extra-build-deps: devscripts git dpkg-cross
          before-build-hook: "dch --local ~${{ inputs.flavor }} 'GitHub build for ${{ inputs.flavor }}'"
          buildpackage-opts: --build=binary --no-sign -d
      - name: Upload deb files
        uses: actions/upload-artifact@v4
        with:
          name: "packages-${{ inputs.flavor }}-${{ inputs.arch }}"
          path: ./debian/artifacts/*
  merge-artefacts:
    runs-on: ubuntu-latest
    needs: build-debs
    steps:
      - name: debian-packages
        uses: actions/upload-artifact/merge@v4
